### ISSUE TITLE
Double '>' with vector in vector error

### ISSUE THREAD

**Issue by mareksubocz** [agrawal-d/competitive-programming-helper#7]
I get an error when i use vector<vector<int>> instead of vector<vector<int> >. I know it's due to old version of g++ being used as a compiler, starting g++-11 would solve the issue. Is there a way to control that? I see on the README screenshots that you declare vectors in the same way.

**Comment by agrawal-d** [comment]
Hi! Thanks for reporting the issue.
I do not seem to have this problem, and can write a vector of vector without space between '<'

I have observed that this problem occurs due to an outdated version of GCC. Have you tried updating GCC yet? When you run GCC, what is the default CPP version used? Try changing that to 11/14/17.

**Comment by agrawal-d** [comment]
Or did I fail to understand you correctly? 
What exactly is the issue? Maybe 2 lines of code with the difference can help?

**Comment by yogeshkumar98103** [comment]
While compiling the file add '-std=c++17' in options array passed in spawn

**Comment by agrawal-d** [comment]
This issue has been resolved in the latest release. You can now add custom compiler flags. Please update your extension.

Closing.
